## Import Numpy


In [19]:
import numpy as np

## The Basics

In [20]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [33]:
b = np.array([[1.0, 2.0, 3.0], [3.0, 4.0, 5.0]])
b

array([[1., 2., 3.],
       [3., 4., 5.]])

In [23]:
a.ndim


1

In [24]:
b.ndim

2

In [25]:
a.shape

(3,)

In [26]:
b.shape

(2, 3)

In [27]:
a.dtype

dtype('int32')

In [28]:
b.dtype

dtype('float64')

In [29]:
a.itemsize

4

In [30]:
b.itemsize


8

In [32]:
c = np.array([[1,0, 2.0, 3.0], [3.0, 4.0, 5.0]])
c

array([list([1, 0, 2.0, 3.0]), list([3.0, 4.0, 5.0])], dtype=object)

## Accessing, changing specific elements, rows and columns


In [36]:
d = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
d

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [43]:
# Get a spcific element
d[1, 5]


13

In [44]:
# Get a specific row

In [45]:
d[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [46]:
d[:, 2]

array([ 3, 10])

In [47]:
# Getting [start index:endindex:stepsize]

d[0, 1:6:2]

array([2, 4, 6])

In [48]:
d[1, 5] = 20
d

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [49]:
d[:, 2] = 5
d

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 20, 14]])

In [54]:
# 3d examo=ple
f = np.array([[[1, 2],[3, 4]],[[5, 6],[7,8]]])
f

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [55]:
# Get specific element(work outside n)

f[0, 1, 1]

4

In [56]:
f[:, 0, 0]

array([1, 5])

In [57]:
# repplace 
f[:, 1, :]
f

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [75]:
x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [79]:
x[:, 2] = 20
x

array([[ 1,  2, 20,  4,  5],
       [ 6,  7, 20,  9, 10]])

## Initializing different types of arrays

In [83]:
# All os matrix
np.zeros(((2, 3, 4)))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [85]:
# All ones matrix
np.ones((4, 2, 2), dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [88]:
# Any other number
np.full((2, 3), 99, 'float32')

array([[99., 99., 99.],
       [99., 99., 99.]], dtype=float32)

In [89]:
# Full_like method
np.full_like(x, 4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [91]:
# Random deciml numbers
np.random.rand(4,2, 3)

array([[[0.74959714, 0.52651884, 0.9671473 ],
        [0.35377638, 0.53908331, 0.46825004]],

       [[0.37471955, 0.85693725, 0.87532013],
        [0.839915  , 0.07017819, 0.96182712]],

       [[0.25714085, 0.72922903, 0.04499256],
        [0.60891456, 0.43741157, 0.83824879]],

       [[0.97731833, 0.09285529, 0.3932704 ],
        [0.68478346, 0.07373516, 0.9455707 ]]])

In [93]:
# Random integer values
np.random.randint(7, size= (3, 3))

array([[1, 2, 2],
       [6, 1, 0],
       [2, 1, 0]])

In [95]:
# Identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [96]:
# Repeat an array
arr = np.array([[1, 2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [106]:
output = np.ones((5, 5))
output

z = np.zeros((3, 3))
z[1, 1]= 9
z
output[1:4, 1:4] = z
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [113]:
r = np.zeros((7, 7))
r
y = np.ones((5, 5))
y
y[2, 2] = 5
y
r[1: -1, 1:-1] = y
r

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 5., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

## Copying arrays warning

In [118]:
k = np.array([1, 2, 3])
m = k.copy()
m[0] = 400
m

array([400,   2,   3])

In [120]:

g= np.array([1, 2, 3, 4, 5])
h= g
h[2] = 20
g

array([ 1,  2, 20,  4,  5])

## Mathemattics

In [130]:
# Linear Algebra

t = np.ones((2, 3))
t
b = np.full((3,2), 2)
b
np.matmul(t, b)

array([[6., 6.],
       [6., 6.]])

In [131]:
# find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

## Statistics

In [132]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [133]:
np.min(stats)

1

In [134]:
np.max(stats)

6

In [135]:
np.max(stats, axis = 0)

array([4, 5, 6])

In [136]:
np.min (stats, axis = 1)

array([1, 4])

In [138]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [142]:

n = np.array(([1, 2, 3, 4, 5], [6, 7, 8, 9, 10]))
n



array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [144]:
v = np.max(n, axis=1).sum()
v

15

## Reorganizing arrays

In [147]:
before = np.array([[1, 2, 3, 4], [5, 6 , 7, 8]])
before




array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [148]:
before.shape

(2, 4)

In [152]:
after = before.reshape((4,2))
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [154]:
# Vertically stacking vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])
np.vstack((v1, v2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [157]:
# Horizontal stacks
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))
h1
h2

np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [160]:
d = np.ones((2, 4))
p = d.reshape((8, 1))
print(p)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


## Miscellaneous

In [161]:
# Load data from file

In [164]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata

array([[ 29.,  97.,  32., 100.,  45.],
       [ 15.,  88.,   5.,  75.,  22.]])

In [166]:
filedata = np.genfromtxt('data.txt', delimiter=',')
output = np.all(filedata < 50, axis=1)

print(output)

[False False]


In [167]:
filedata = np.genfromtxt('data.txt', delimiter=',')
output = filedata[filedata < 50]

print(output)

[29. 32. 45. 15.  5. 22.]


##### Boolean Masking and advanced Masking

In [ ]:
filedata > 50
filedata > = 50
filedata(filedata > 50)
np.any(filedata > 50, axis = 0)
((filedata > 50) & (fildata < 100))

In [163]:
# Index with a list in numpy
s = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
s[[1, 2, 8]]

array([2, 3, 9])